% fact(Relation, Subject, Object, Count).
fact('adjacent_to', 'baseball_diamond', 'soccer_ball_field', 125).
fact('adjacent_to', 'large_vehicle', 'small_vehicle', 73288).
fact('adjacent_to', 'plane', 'plane', 76253).
fact('adjacent_to', 'swimming_pool', 'Ground_Track_Field', 20).
fact('adjacent_to', 'tennis_court', 'basketball_court', 502).
fact('cooccurs', 'Bridge', 'Bridge', 165770).
fact('cooccurs', 'Bridge', 'Ground_Track_Field', 13367).
fact('cooccurs', 'Bridge', 'baseball_diamond', 4329).
fact('cooccurs', 'Bridge', 'basketball_court', 2478).
fact('cooccurs', 'Bridge', 'harbor', 7145).
fact('cooccurs', 'Bridge', 'helicopter', 697).
fact('cooccurs', 'Bridge', 'large_vehicle', 8521).
fact('cooccurs', 'Bridge', 'plane', 24119).
fact('cooccurs', 'Bridge', 'roundabout', 3835).
fact('cooccurs', 'Bridge', 'ship', 108297).
fact('cooccurs', 'Bridge', 'small_vehicle', 2925).
fact('cooccurs', 'Bridge', 'soccer_ball_field', 1731).
fact('cooccurs', 'Bridge', 'storage_tank', 59323).
fact('cooccurs', 'Bridge', 'swimming_pool', 1211).
fact('cooccurs', 'Bridge', 'tennis_court', 1108).
fact('cooccurs', 'Ground_Track_Field', 'Ground_Track_Field', 4338).
fact('cooccurs', 'Ground_Track_Field', 'baseball_diamond', 3284).
fact('cooccurs', 'Ground_Track_Field', 'basketball_court', 1875).
fact('cooccurs', 'Ground_Track_Field', 'harbor', 852).
fact('cooccurs', 'Ground_Track_Field', 'helicopter', 82).
fact('cooccurs', 'Ground_Track_Field', 'large_vehicle', 5094).
fact('cooccurs', 'Ground_Track_Field', 'plane', 6547).
fact('cooccurs', 'Ground_Track_Field', 'roundabout', 1325).
fact('cooccurs', 'Ground_Track_Field', 'ship', 9235).
fact('cooccurs', 'Ground_Track_Field', 'small_vehicle', 20182).
fact('cooccurs', 'Ground_Track_Field', 'soccer_ball_field', 2048).
fact('cooccurs', 'Ground_Track_Field', 'storage_tank', 9570).
fact('cooccurs', 'Ground_Track_Field', 'swimming_pool', 1769).
fact('cooccurs', 'Ground_Track_Field', 'tennis_court', 2431).
fact('cooccurs', 'baseball_diamond', 'baseball_diamond', 7812).
fact('cooccurs', 'baseball_diamond', 'basketball_court', 662).
fact('cooccurs', 'baseball_diamond', 'harbor', 1352).
fact('cooccurs', 'baseball_diamond', 'helicopter', 115).
fact('cooccurs', 'baseball_diamond', 'large_vehicle', 9847).
fact('cooccurs', 'baseball_diamond', 'plane', 17449).
fact('cooccurs', 'baseball_diamond', 'roundabout', 1363).
fact('cooccurs', 'baseball_diamond', 'ship', 13731).
fact('cooccurs', 'baseball_diamond', 'small_vehicle', 88620).
fact('cooccurs', 'baseball_diamond', 'soccer_ball_field', 2512).
fact('cooccurs', 'baseball_diamond', 'storage_tank', 3667).
fact('cooccurs', 'baseball_diamond', 'swimming_pool', 1562).
fact('cooccurs', 'baseball_diamond', 'tennis_court', 9950).
fact('cooccurs', 'basketball_court', 'basketball_court', 5083).
fact('cooccurs', 'basketball_court', 'harbor', 634).
fact('cooccurs', 'basketball_court', 'helicopter', 52).
fact('cooccurs', 'basketball_court', 'large_vehicle', 4168).
fact('cooccurs', 'basketball_court', 'plane', 2597).
fact('cooccurs', 'basketball_court', 'roundabout', 324).
fact('cooccurs', 'basketball_court', 'ship', 6552).
fact('cooccurs', 'basketball_court', 'small_vehicle', 16279).
fact('cooccurs', 'basketball_court', 'soccer_ball_field', 1807).
fact('cooccurs', 'basketball_court', 'storage_tank', 5948).
fact('cooccurs', 'basketball_court', 'swimming_pool', 3075).
fact('cooccurs', 'basketball_court', 'tennis_court', 6213).
fact('cooccurs', 'harbor', 'harbor', 748760).
fact('cooccurs', 'harbor', 'helicopter', 35).
fact('cooccurs', 'harbor', 'large_vehicle', 35320).
fact('cooccurs', 'harbor', 'plane', 11612).
fact('cooccurs', 'harbor', 'roundabout', 3019).
fact('cooccurs', 'harbor', 'ship', 1179554).
fact('cooccurs', 'harbor', 'small_vehicle', 586272).
fact('cooccurs', 'harbor', 'soccer_ball_field', 1051).
fact('cooccurs', 'harbor', 'storage_tank', 24488).
fact('cooccurs', 'harbor', 'swimming_pool', 83745).
fact('cooccurs', 'harbor', 'tennis_court', 4662).
fact('cooccurs', 'helicopter', 'helicopter', 64605).
fact('cooccurs', 'helicopter', 'large_vehicle', 15230).
fact('cooccurs', 'helicopter', 'plane', 296230).
fact('cooccurs', 'helicopter', 'roundabout', 399).
fact('cooccurs', 'helicopter', 'ship', 1184).
fact('cooccurs', 'helicopter', 'small_vehicle', 151581).
fact('cooccurs', 'helicopter', 'soccer_ball_field', 71).
fact('cooccurs', 'helicopter', 'storage_tank', 517).
fact('cooccurs', 'helicopter', 'swimming_pool', 462).
fact('cooccurs', 'helicopter', 'tennis_court', 63).
fact('cooccurs', 'large_vehicle', 'large_vehicle', 2360625).
fact('cooccurs', 'large_vehicle', 'plane', 436106).
fact('cooccurs', 'large_vehicle', 'roundabout', 9118).
fact('cooccurs', 'large_vehicle', 'ship', 570124).
fact('cooccurs', 'large_vehicle', 'small_vehicle', 2975833).
fact('cooccurs', 'large_vehicle', 'soccer_ball_field', 8442).
fact('cooccurs', 'large_vehicle', 'storage_tank', 213566).
fact('cooccurs', 'large_vehicle', 'swimming_pool', 23096).
fact('cooccurs', 'large_vehicle', 'tennis_court', 22174).
fact('cooccurs', 'plane', 'plane', 1187033).
fact('cooccurs', 'plane', 'roundabout', 15934).
fact('cooccurs', 'plane', 'ship', 202891).
fact('cooccurs', 'plane', 'small_vehicle', 763601).
fact('cooccurs', 'plane', 'soccer_ball_field', 5485).
fact('cooccurs', 'plane', 'storage_tank', 39250).
fact('cooccurs', 'plane', 'swimming_pool', 78500).
fact('cooccurs', 'plane', 'tennis_court', 11536).
fact('cooccurs', 'roundabout', 'roundabout', 3754).
fact('cooccurs', 'roundabout', 'ship', 30238).
fact('cooccurs', 'roundabout', 'small_vehicle', 40986).
fact('cooccurs', 'roundabout', 'soccer_ball_field', 1267).
fact('cooccurs', 'roundabout', 'storage_tank', 7116).
fact('cooccurs', 'roundabout', 'swimming_pool', 8341).
fact('cooccurs', 'roundabout', 'tennis_court', 1496).
fact('cooccurs', 'ship', 'ship', 12206383).
fact('cooccurs', 'ship', 'small_vehicle', 3293564).
fact('cooccurs', 'ship', 'soccer_ball_field', 21223).
fact('cooccurs', 'ship', 'storage_tank', 217819).
fact('cooccurs', 'ship', 'swimming_pool', 492771).
fact('cooccurs', 'ship', 'tennis_court', 56256).
fact('cooccurs', 'small_vehicle', 'small_vehicle', 10389769).
fact('cooccurs', 'small_vehicle', 'soccer_ball_field', 62249).
fact('cooccurs', 'small_vehicle', 'storage_tank', 142527).
fact('cooccurs', 'small_vehicle', 'swimming_pool', 188153).
fact('cooccurs', 'small_vehicle', 'tennis_court', 208342).
fact('cooccurs', 'soccer_ball_field', 'soccer_ball_field', 1327).
fact('cooccurs', 'soccer_ball_field', 'storage_tank', 2742).
fact('cooccurs', 'soccer_ball_field', 'swimming_pool', 6815).
fact('cooccurs', 'soccer_ball_field', 'tennis_court', 6309).
fact('cooccurs', 'storage_tank', 'storage_tank', 1316316).
fact('cooccurs', 'storage_tank', 'swimming_pool', 6865).
fact('cooccurs', 'storage_tank', 'tennis_court', 2393).
fact('cooccurs', 'swimming_pool', 'swimming_pool', 363062).
fact('cooccurs', 'swimming_pool', 'tennis_court', 16058).
fact('cooccurs', 'tennis_court', 'tennis_court', 29878).
fact('located_near', 'helicopter', 'plane', 917).
fact('located_near', 'roundabout', 'small_vehicle', 2970).
fact('located_near', 'ship', 'harbor', 196281).
fact('located_near', 'small_vehicle', 'Ground_Track_Field', 3936).
fact('located_near', 'small_vehicle', 'baseball_diamond', 1030).
fact('located_near', 'small_vehicle', 'basketball_court', 489).
fact('located_near', 'small_vehicle', 'roundabout', 2970).
fact('located_near', 'small_vehicle', 'small_vehicle', 406454).
fact('located_near', 'small_vehicle', 'soccer_ball_field', 4936).
fact('located_near', 'small_vehicle', 'tennis_court', 4927).
fact('located_near', 'storage_tank', 'harbor', 396).
fact('located_on', 'large_vehicle', 'Bridge', 5).
