# Sample configuration for building the knowledge graph locally.
model_path: /path/to/project/artifacts/best.pt
knowledge_graph_dir: /path/to/project/knowledge_graph
data_splits:
  train: /path/to/project/data/images/train
  val: /path/to/project/data/images/val
confidence_threshold: 0.25
slice_height: 1024
slice_width: 1024
overlap_height: 0.25
overlap_width: 0.25
facts_filename: facts.pl
graph_filename: knowledge_graph_visuals.png
