# Sample configuration for running SAHI predictions locally.
model_path: /path/to/project/artifacts/best.pt
test_images_dir: /path/to/project/data/images/val
output_predictions_dir: /path/to/project/predictions
confidence_threshold: 0.05
slice_height: 1024
slice_width: 1024
overlap_height: 0.25
overlap_width: 0.25
