name: Dependency health check

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  smoke-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y swi-prolog

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Byte-compile source tree
        run: |
          python -m compileall training.py pipeline src
